# Generated by Django 4.1.6 on 2023-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=30)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=254)),
                ('message', models.CharField(default='knkjnkjnknkn', max_length=500)),
            ],
        ),
    ]
